modLoader="javafml" #mandatory

loaderVersion="[36,)" #mandatory

license="GNU GENERAL PUBLIC LICENSE Version 3, 29 June 2007" #mandatory

[[mods]] #mandatory

itemIcon="ironfurnaces:iron_furnace"

modId="ironfurnaces" #mandatory

version="${file.jarVersion}" #mandatory

displayName="Iron Furnaces" #mandatory

displayURL="https://www.curseforge.com/minecraft/mc-mods/iron-furnaces/" #optional

credits="Java, JetBrains, Minecraft, MinecraftForge, LexManos, mezz, Ellpeck, KingLemming" #optional

authors="Qelifern (pizzaatime), XenoMustache" #optional

description='''
IronFurnaces is a mod that adds various tiers of metal furnaces that will smelt away to your desires.
'''

[[dependencies.ironfurnaces]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.ironfurnaces]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5, 1.17.1]"
    ordering="NONE"
    side="BOTH"
[[dependencies.ironfurnaces]]
   modId="jei"
   mandatory=false
   versionRange="[7,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.ironfurnaces]]
   modId="ftbguilibrary"
   mandatory=false
   versionRange="[1,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.ironfurnaces]]
  modId="allthemodium"
  mandatory=false
  versionRange="[1.1,)"
  ordering="NONE"
  side="BOTH"
[[dependencies.ironfurnaces]]
    modId="pmmo"
    mandatory=false
    versionRange="[1.16.5-3,)"
    ordering="NONE"
    side="BOTH"
